#!groovy

// Generated by IBM TransformationAdvisor
// Wed Nov 07 10:30:07 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'customerorderservicesapp'
    mvnCommands = '--version'
    test='false'
}